#undef DEBOUNCE
#define DEBOUNCE 5

#undef TAPPING_TERM
#define TAPPING_TERM 204


#define COMBO_TERM 49

#define USB_SUSPEND_WAKEUP_DELAY 0
#define LAYER_STATE_16BIT
#undef DYNAMIC_KEYMAP_LAYER_COUNT
#define DYNAMIC_KEYMAP_LAYER_COUNT 2

#define RGB_MATRIX_STARTUP_SPD 60
